object Dependencies {
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${DependenciesVersions.KOTLIN}"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${DependenciesVersions.COROUTINES}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${DependenciesVersions.COROUTINES}"
    const val ROOM = "androidx.room:room-runtime:${DependenciesVersions.ROOM}"
    const val ROOM_KTX = "androidx.room:room-ktx:${DependenciesVersions.ROOM}"
    const val RECYCLE_VIEW = "androidx.recyclerview:recyclerview:${DependenciesVersions.RECYCLE_VIEW}"
    const val NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${DependenciesVersions.NAVIGATION}"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx:${DependenciesVersions.NAVIGATION}"
    const val LIFECYCLE_EXTENSIONS = "androidx.lifecycle:lifecycle-extensions:${DependenciesVersions.LIFECYCLE}"
    const val LIFECYCLE_VIEWMODEL = "androidx.lifecycle:lifecycle-viewmodel-ktx:${DependenciesVersions.LIFECYCLE}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${DependenciesVersions.APPCOMPAT}"
    const val CORE_KTX = "androidx.core:core-ktx:${DependenciesVersions.CORE_KTX}"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:${DependenciesVersions.FRAGMENT_KTX}"
    const val CONSTRAIN_LAYOUT = "androidx.constraintlayout:constraintlayout:${DependenciesVersions.CONSTRAIN_LAYOUT}"
    const val PAGING = "androidx.paging:paging-runtime-ktx:${DependenciesVersions.PAGING}"
    const val DAGGER = "com.google.dagger:dagger:${DependenciesVersions.DAGGER}"
    const val TIMBER = "com.jakewharton.timber:timber:${DependenciesVersions.TIMBER}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${DependenciesVersions.RETROFIT}"
    const val RETROFIT_CONVERTER = "com.squareup.retrofit2:converter-gson:${DependenciesVersions.RETROFIT}"
    const val LOGGING = "com.squareup.okhttp3:logging-interceptor:${DependenciesVersions.LOGGING}"
    const val MOSHI = "com.squareup.moshi:moshi:${DependenciesVersions.MOSHI}"
    const val MOSHI_KTX = "com.squareup.moshi:moshi-kotlin:${DependenciesVersions.MOSHI}"
    const val GLIDE = "com.github.bumptech.glide:glide:${DependenciesVersions.GLIDE}"
    const val CRASHLYTICS = "com.crashlytics.sdk.android:crashlytics:${DependenciesVersions.CRASHLYTICS}"
    const val PRAY_CORE = "com.google.android.play:core:${DependenciesVersions.PRAY_CORE}"
}
