object DependenciesVersions {
    const val KOTLIN = "1.3.41"
    const val APPCOMPAT = "1.0.2"
    const val MATERIAL = "1.1.0-beta01"
    const val COROUTINES = "1.3.0-RC"
    const val ROOM = "2.2.0-rc01"
    const val RECYCLE_VIEW = "1.1.0-alpha06"
    const val NAVIGATION = "2.0.0"
    const val LIFECYCLE = "2.0.0"
    const val CORE_KTX = "1.0.2"
    const val FRAGMENT_KTX = "1.2.0-alpha02"
    const val CONSTRAIN_LAYOUT = "1.1.3"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0-alpha02"
    const val PAGING = "2.1.0"
    const val DAGGER = "2.24"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.6.1"
    const val LOGGING = "4.1.0"
    const val MOSHI = "1.8.0"
    const val GLIDE = "4.9.0"
    const val CRASHLYTICS = "2.10.1"
    const val PLAY_CORE = "1.6.1"
    const val LEAKCANARY = "2.0-beta-2"
    const val DATABINDING = "3.1.4"

    // Tests
    const val JUNIT = "4.12"
    const val ROBOELECTRIC = "4.3"
    const val MOCKITO = "2.1.0"
    const val ASSERTJ = "3.13.2"
    const val ESPRESSO = "3.2.0"
    const val RUNNER = "1.2.0"
    const val RULES = "1.2.0"
}

